---
- name: Copy default Jail
  template:
    #src: templates/fail2ban.local.j2
    src: 'fail2ban.local.j2'
    dest: "{{ fail2ban_jail_dir }}/fail2ban.local"
  notify:
  - Restart Fail2Ban

# - name: Copy filters
#   template:
#     #src: templates/{{ item }}_filter.conf.j2
#     src: '{{ item }}_filter.conf.j2'
#     dest: "{{ fail2ban_jail_dir }}/{{ item }}.conf"
#   with_items: "{{ fail2ban_modules }}"
#   #ignore_errors: yes
#   notify:
#   - Restart Fail2Ban
    
- name: Copy jails
  template:
    #src: templates/{{ item }}_jail.local.j2
    src: '{{ item }}_jail.local.j2'
    dest: "{{ fail2ban_jail_dir }}/{{ item }}.local"
  with_items: "{{ fail2ban_modules }}"
  notify:
  - Restart Fail2Ban

- name: Configure logrotate
  template:
    src: 'etc_logrotate.d_fail2ban.j2'
    dest: "{{ fail2ban_config_logrotate }}"
  when: fail2ban_logrotate.configure|bool
  notify: Restart Fail2Ban

